apiVersion: v1
kind: Service

metadata:
  name: catalogue-service
  namespace: default

spec:
  clusterIP: None
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: catalogue