apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  labels:
    app: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: vipuldhand/frontend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - name: frontend-config-volume
            mountPath: /app/config.json
            subPath: config.json
      volumes:
      - name: frontend-config-volume
        configMap:
          name: frontend-config