apiVersion: apps/v1
kind: Deployment

metadata:
  name: voting
  labels:
    app: voting

spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting

  template:
    metadata:
      labels:
        app: voting

    spec:
      containers:
      - name: voting
        image: vipuldhand/voting:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "256Mi"
          cpu: "200m"
        requests:
          memory: "128Mi"
          cpu: "100m"