{{- $rollout := (.Values.frontend.rollout | default dict) }}
{{- if ($rollout.enabled | default false) }}

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}

  strategy:
            {{- $rollout := (.Values.frontend.rollout | default dict) }}
            {{- if and ($rollout.enabled | default false) (eq ($rollout.mode | default "") "canary") }}
            canary:
              stableService: {{ .Release.Name }}-frontend-stable
              canaryService: {{ .Release.Name }}-frontend-canary
              steps:
                - setWeight: 20
                - pause: { duration: 5s }
                - setWeight: 50
                - pause: { duration: 5s }
                - setWeight: 100
              analysis:
                templates:
                  - templateName: success-rate-check
            {{- end }}

            {{- $rollout := (.Values.frontend.rollout | default dict) }}
            {{- if and ($rollout.enabled | default false) (eq ($rollout.mode | default "") "bluegreen") }}
            bluegreen:
              activeService: {{ .Release.Name }}-frontend-active
              previewService: {{ .Release.Name }}-frontend-preview
              autoPromotionEnabled: false
            {{- end }}

{{- end }}