{{- $rollout := (.Values.frontend.rollout | default dict) }}
{{- if and ($rollout.enabled | default false) (eq ($rollout.mode | default "") "bluegreen") }}
  
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-active
spec:
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-preview
spec:
  selector: 
    app: {{ .Release.Name }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}

{{- end }}