apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend

    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.frontend.port }}

          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: frontend-config-volume
              mountPath: /app/config.json
              subPath: config.json
      volumes:
        - name: frontend-config-volume
          configMap:
            name: {{ .Release.Name }}-frontend-config
  strategy:
          {{- if eq .Values.rollout.mode "canary" }}
          canary:
            stableService: {{ .Release.Name }}-frontend-stable
            canaryService: {{ .Release.Name }}-frontend-canary
            steps:
              - setWeight: 20
              - pause: { duration: 5s }
              - setWeight: 50
              - pause: { duration: 5s }
              - setWeight: 100
            analysis:
              templates:
                - templateName: success-rate-check
          {{- end }}

          {{- if eq .Values.rollout.mode "bluegreen" }}
          bluegreen:
            activeService: {{ .Release.Name }}-frontend-active
            previewService: {{ .Release.Name }}-frontend-preview
            autoPromotionEnabled: false
          {{- end }}