{{- if and .Values.frontend.rollout.enabled (eq .Values.frontend.rollout.mode "canary") }}

#Stable Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-stable
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
---

#Canary Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-canary
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }} 

{{- end }}