{{- $frontend := .Values.frontend | default dict }}
{{- $rollout := $frontend.rollout | default dict }}

{{- if not ($rollout.enabled | default false) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      {{- if eq .Values.frontend.serviceType "NodePort" }}
      nodePort: {{ .Values.frontend.nodePort }}
      {{- end }}

{{- end }}