{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend-stable
                port:
                  number: {{ .Values.frontend.port }}

          # Catalogue Service
          - path: /api/catalogue
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-catalogue-stable
                port:
                  number: {{ .Values.catalogue.port }}

          # Recommendation Service
          - path: /api/recommend
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-recommendation-stable
                port:
                  number: {{ .Values.recommendation.port }}

          # Voting Service
          - path: /api/vote
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-voting-stable
                port:
                  number: {{ .Values.voting.port }}
{{- end }}