{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                {{- $frontend := .Values.frontend | default dict }}
                {{- $rollout := $frontend.rollout | default dict }}

                {{- if and ($rollout.enabled | default false) (eq ($rollout.mode | default "") "canary") }}
                name: {{ .Release.Name }}-frontend-stable
                port:
                  number: {{ .Values.frontend.port }}

                {{- else if and ($rollout.enabled | default false) (eq ($rollout.mode | default "") "bluegreen") }}
                name: {{ .Release.Name }}-frontend-active

                {{- else }}
                name: {{ .Release.Name }}-frontend-service
                port:
                  number: {{ .Values.frontend.port }}
                {{- end }}

          # Catalogue Service
          - path: /api/catalogue
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-catalogue-service
                port:
                  number: {{ .Values.catalogue.port }}

          # Recommendation Service
          - path: /api/recommend
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-recommendation-service
                port:
                  number: {{ .Values.recommendation.port }}

          # Voting Service
          - path: /api/vote
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-voting-service
                port:
                  number: {{ .Values.voting.port }}
{{- end }}