frontend:
  service:
    type: ClusterIP
  replicas: 1
  image: vipuldhand/frontend:e6208b9addcb557d04888fca3126d1624f8692eb
  port: 3000
  config:
    version: "1.0.0"
    productsApiBaseUri: "http://craftista-catalogue-service:5000"
    recommendationBaseUri: "http://craftista-recommendation-service:8080"
    votingBaseUri: "http://craftista-voting-service:8080"
catalogue:
  replicas: 1
  image: vipuldhand/frontend:e6208b9addcb557d04888fca3126d1624f8692eb
  port: 5000
recommendation:
  replicas: 1
  image: vipuldhand/frontend:e6208b9addcb557d04888fca3126d1624f8692eb
  port: 8080
voting:
  replicas: 1
  image: vipuldhand/frontend:e6208b9addcb557d04888fca3126d1624f8692eb
  port: 8080
ingress:
  enabled: true
  host: craftista.local
rollout:
  canaryEnabled: false
  blueGreenEnabled: true