frontend:
  service:
    type: ClusterIP
  replicas: 1
  image: vipuldhand/frontend:c37d6f04b2e6dbec858c77874894129cc1c189f7
  port: 3000
  config:
    version: "1.0.0"
    productsApiBaseUri: "http://craftista-catalogue-service:5000"
    recommendationBaseUri: "http://craftista-recommendation-service:8080"
    votingBaseUri: "http://craftista-voting-service:8080"
catalogue:
  replicas: 1
  image: vipuldhand/frontend:c37d6f04b2e6dbec858c77874894129cc1c189f7
  port: 5000
recommendation:
  replicas: 1
  image: vipuldhand/frontend:c37d6f04b2e6dbec858c77874894129cc1c189f7
  port: 8080
voting:
  replicas: 1
  image: vipuldhand/frontend:c37d6f04b2e6dbec858c77874894129cc1c189f7
  port: 8080
ingress:
  enabled: true
  host: craftista.local
rollout:
  enabled: true