frontend:
  service:
    type: ClusterIP
  replicas: 1
  image: vipuldhand/frontend:995aa732b04a3379e70820111e84072ee60ac0f7
  port: 3000
  config:
    version: "1.0.0"
    productsApiBaseUri: "http://craftista-catalogue-service:5000"
    recommendationBaseUri: "http://craftista-recommendation-service:8080"
    votingBaseUri: "http://craftista-voting-service:8080"
    rollout:
      enabled: true
      mode: canary   # canary | bluegreen | standard
catalogue:
  replicas: 1
  image: vipuldhand/frontend:995aa732b04a3379e70820111e84072ee60ac0f7
  port: 5000
  rollout:
    enabled: false
recommendation:
  replicas: 1
  image: vipuldhand/frontend:995aa732b04a3379e70820111e84072ee60ac0f7
  port: 8080
  rollout:
    enabled: false
voting:
  replicas: 1
  image: vipuldhand/frontend:995aa732b04a3379e70820111e84072ee60ac0f7
  port: 8080
  rollout:
    enabled: false
ingress:
  enabled: true
  host: craftista.local