name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, catalogue, recommendation, voting]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project structure (debug)
        run: ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ matrix.service }} .