name: CI
permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/craftista-chart/values.yaml'  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, catalogue, recommendation, voting]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Show project structure (debug)
        run: ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          docker build \
           -t vipuldhand/${{ matrix.service }}:latest \
           -t vipuldhand/${{ matrix.service }}:${{ github.sha }} \
           .

          docker push vipuldhand/${{ matrix.service }}:latest
          docker push vipuldhand/${{ matrix.service }}:${{ github.sha }}

      - name: Update Helm values for frontend
        if: matrix.service == 'frontend'
        run: |
          sed -i "s|image: .*|image: vipuldhand/frontend:${{ github.sha }}|" helm/craftista-chart/values.yaml
      
      - name: Setup Git auth
        if: matrix.service == 'frontend'
        run: |
          git config --global --add safe.directory /github/workspace
          
      - name: Commit updated values.yaml
        if: matrix.service == 'frontend'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm/craftista-chart/values.yaml
          git commit -m "update frontend image to ${{ github.sha }}"
          git push